import os
import uuid
import requests
from galtea import Galtea
from dotenv import load_dotenv

# Load variables from .env file
load_dotenv()

# Initialize the Galtea client with your API key from .env
GALTEA_API_KEY = os.getenv("GALTEA_API_KEY")
if not GALTEA_API_KEY:
    raise ValueError("Missing GALTEA_API_KEY environment variable. Please add it to your .env file.")

galtea = Galtea(api_key=GALTEA_API_KEY)

# Generate a unique thread ID for the session
session_id = str(uuid.uuid4())

def my_agent(messages: list[dict]) -> str:
    """Wrapper function that Galtea will call to test our agent."""
    # messages follows the standard chat format:
    # [{"role": "user", "content": "..."}, {"role": "assistant", "content": "..."}, ...]
    user_message = messages[-1]['content']
    
    url = "http://localhost:8000/api/agent/chat"
    payload = {
        "thread_id": session_id,
        "message": user_message
    }
    
    try:
        response = requests.post(url, json=payload, timeout=30)
        response.raise_for_status()
        data = response.json()
        # Return the actual text reply from our orchestrator
        return data.get("reply", "No reply found")
    except Exception as e:
        return f"Error connecting to agent: {str(e)}"

def run_eval():
    print("Fetching product and version...")
    # Fetch the product dynamically by listing and picking the first one
    products = galtea.products.list()
    if not products:
        raise ValueError("No products found in your Galtea account. Please create one on the dashboard.")
    
    product = products[0]
    print(f"Found product: '{product.name}' (ID: {product.id})")
    
    # List versions for this product and pick the first one
    versions = galtea.versions.list(product_id=product.id)
    if not versions:
        raise ValueError(f"No versions found for product {product.name}. Please create one.")
        
    version = versions[0]
    
    print(f"Running evaluation on version {version.id}...")
    
    # Run evaluation — metrics and tests come from your specifications
    result = galtea.evaluations.run(
        version_id=version.id,
        agent=my_agent,
        # The specifications generated by Galtea during your onboarding
        specification_ids=[
            "specification_qpsum9v9py8daxrhzhu2klp4",
            "specification_wkqfghprqdxhuhgyasrdd1lp",
            "specification_kcvjaplgbss13h1k0tjf6hzn"
        ],
    )
    
    print("Evaluation finished!")
    print(f"Result data: {result}")
    
    if isinstance(result, dict):
        count = result.get('testCaseCount', 0)
        print(f"Launched {count} test cases.")
        if count == 0:
            print("WARNING: 0 test cases were launched! This usually means your specifications don't have any datasets yet, or the datasets haven't finished generating test cases.")
    
    print("Check the Galtea dashboard for the results.")

if __name__ == "__main__":
    run_eval()
